### ISSUE TITLE
The repo at https://github.com/mozilla/ispdb/ might be confused with this one

### ISSUE THREAD

**Issue by mendel5** [thundernest/autoconfig#24]
Thanks to the awesome support by Ryan @ryanleesipes I'm quite sure that an issue I have with a German email hosting provider might be fixed by changing its entry in the Thunderbird ISPDB.

When I was looking for the source repository of the ISPDB ([https://autoconfig.thunderbird.net/v1.1/](https://autoconfig.thunderbird.net/v1.1/)) I previously found the repository at https://github.com/mozilla/ispdb/ . But given the fact that its last commit was in August 2012 I assumed that the ISPDB is not based on the repo at https://github.com/mozilla/ispdb/ .

Maybe a small explanation and link can be added to the README file at https://github.com/mozilla/ispdb/blob/master/README.md to guide people like me to the correct repo at https://github.com/thundernest/autoconfig ?

**Comment by clokep** [comment]
We should probably ask for mozilla/ispdb to be archived as well, if it is no longer used.

**Comment by Sancus** [comment]
I filed a bug to get that old repo archived and a link to this repo added in the README.

https://bugzilla.mozilla.org/show_bug.cgi?id=1744817

**Comment by Sancus** [comment]
It is done.

**Comment by mendel5** [comment]
Thank you very much, @Sancus !
