### ISSUE TITLE
Two dead links in the README file

### ISSUE THREAD

**Issue by mendel5** [thundernest/autoconfig#26]
In the README file at https://github.com/thundernest/autoconfig/blob/master/README.md there is this list:
> Be sure to read the docs below before changing anything:
> * [Autoconfig mechanism documentation](https://developer.mozilla.org/en/Thunderbird/Autoconfiguration), including file format definition and explanations.
> * [How to configure your domain](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration#Configuration_server_at_ISP) without being added to the ISPDB here. This is useful for small ISPs and domains that are not open to the public.

Unfortunately both pages return a 404 error (Page not found).

**Comment by benbucksch** [comment]
Yes, the MDN team sadly didn't read https://www.w3.org/Provider/Style/URI.html and keep breaking links all the time. :-(

I'm getting a little tired chasing them once a year.

**Comment by Sancus** [comment]
I really dislike the way the MDN team has handled their content changes. The least they could have done is make a list of links to web.archive.org and put a banner on disappeared pages saying "we don't host this content anymore, sorry, but you can find it here".

I should be able to put those articles on wiki.mozilla.org, I'll do this soon.

**Comment by mendel5** [comment]
Thank you, Sancus!

> disappeared pages

Does that mean they just deleted Thunderbird's documentation? 🤨

**Comment by Sancus** [comment]
> Thank you, Sancus!
> 
> > disappeared pages
> 
> Does that mean they just deleted Thunderbird's documentation? 🤨

It happened a while ago, but we moved most of the developer documentation to https://developer.thunderbird.net/ before that anyhow. It's only an issue for certain things like this that slipped through the cracks.

**Comment by mendel5** [comment]
> It's only an issue for certain things like this that slipped through the cracks.

Ok, thanks for the explanation!

**Comment by MTRNord** [comment]
Is this now completely gone or am I just blind while looking at https://developer.thunderbird.net ?

**Comment by bbhtt** [comment]
> Is this now completely gone ...

There is a snapshot of the page on Internet archive, this is the last one with the content https://web.archive.org/web/20210624004729/https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration

**Comment by jhaand** [comment]
It would be nice if the documentation was fixed. Choose to either update the content on https://developer.thunderbird.net or remove the links from the README.md.

**Comment by HLFH** [comment]
I currently have the archive here: https://hlfh.github.io/autoconfiguration/.

**Comment by SphinxKnight** [comment]
MDN archived content is in https://github.com/mdn/archived-content/

e.g. https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/thunderbird/autoconfiguration/raw.html

**Comment by SphinxKnight** [comment]
the page also lives under https://www.bucksch.org/1/projects/thunderbird/autoconfiguration/

**Comment by SphinxKnight** [comment]
https://github.com/thundernest/autoconfig/pull/54 could help fix this.

**Comment by benbucksch** [comment]
FIXED in commit a061b30a7bb
