### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [thundernest/autoconfig#28]
Please add the following [Github topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) to this repository:
- https://github.com/topics/mozilla
- https://github.com/topics/thunderbird
- https://github.com/topics/autoconfig
- https://github.com/topics/ispdb
- https://github.com/topics/imap
- https://github.com/topics/pop3
- https://github.com/topics/smtp

Thanks!

**Comment by Sancus** [comment]
Sure.
