### ISSUE TITLE
Configuración de educa.madrid.org

### ISSUE THREAD

**Issue by sergiolobodelolmo** [thundernest/autoconfig#78]
I'm sorry. I made a mistake with this comment.

**Comment by sergiolobodelolmo** [comment]
Hello:
We made a Pull Request (#70) and you answered that you apply an earlier one (#44).
But it isn't working well. When I try to configure Thunderbird with our domain, it doesn't work.
Is it possible to apply de file that I requested? Is there any problem with it that we should repair?
We wait for your answer.
Thank you

**Comment by benbucksch** [comment]
Hi Sergio,
Could you please describe:
1. What precisely you did - every keypress and mouse click, after you started the Thunderbird email config dialog.
2. What happened.
2.1. What configuation did you get
2.2. If it didn't work, what exactly didn't work.
2.3. Please include the output of the Error Console (only the part from the config dialog) and the relevant Network requests from the Developer tools.
4. What you think should have happened instead.

Please note that this is not a support forum. This is for large ISPs and IT administrators. If you're not able to provide helpful information, I cannot do anything.

**Comment by sergiolobodelolmo** [comment]
I have test it again and now it works properly. I don't know what has happened. Anyway, thank you.
